### ISSUE TITLE
Small folder uses symbolic icon, invisible

### ISSUE THREAD

**Issue by germanfr** [cbrnix/Newaita#128] opened 2019-09-22 11:23 UTC
Small folder icons are now like their symbolic version, which you can choose either it to be black or white. It is not only a consistency problem with other icons and itself in other sizes, but it also makes the icons unusable and invisible. Either if I use the dark or light version there is one place where the icons are not visible. 

Please, revert to the previous icons. They looked fantastic.

Here are some screenshots to illustrate the problem:

**When I use the dark version:**
![Screenshot from 2019-09-22 13-20-32](https://user-images.githubusercontent.com/10391266/65386420-c9cd6180-dd3b-11e9-98ee-b099e566a7e3.png)

**When I use the light version:**
![Screenshot from 2019-09-22 13-16-46](https://user-images.githubusercontent.com/10391266/65386395-7eb34e80-dd3b-11e9-8ea9-2b7bf1bf0adc.png)

**Comment by cbrnix** [comment] 2019-09-23 03:12
This is not a bug. Use a theme on a light background for a light background.

**Comment by germanfr** [comment] 2019-09-23 04:45
That is not possible, as I exposed. Backgrounds are not always the same color in most themes.

**Comment by cbrnix** [comment] 2019-09-23 05:20
Just as it is impossible to create an icon theme that takes into account all the fantasies of theme creators.  You have a light background.  Use Newaita, then the icons on a light background will be dark.  If the background is dark, use Newaita Dark.  There are no other options.
Look this https://github.com/cbrnix/Newaita/issues/115
and you will understand that there are wishes that contradict each other.  Sometimes you need to choose priority tasks

**Comment by germanfr** [comment] 2019-09-23 05:53
Please don't be condescending with me. It's not fantasies of theme creators. White windows and dark panels is the standard on most themes, even on the default GNOME theme. 

I agree that places icons inside very small folders are not distinguishable, but I don't think this is the right solution. If the goal is to make icons more visible this is worst. I would go with what the elementary icon theme does. Use the representative icon without the folder like you do but coloured. That would be fantastic. :smile:

**Comment by cbrnix** [comment] 2019-09-23 05:58
You are using Newaita-dark while you have a light theme, why are you surprised that the icons are light on a light background?  Use Newaita and these icons will be dark gray.  I do not understand the problem

**Comment by germanfr** [comment] 2019-09-23 06:01
I am not using Newaita-dark nor light. The problem is that if I use the normal Newaita the icons are not visible in the panel, and if I use the other one the icons are not visible in Nautilus.

**Comment by germanfr** [comment] 2019-09-23 06:03
If I use the normal Newaita icons in Nautilus look ok but in the panel look like in the first screenshot.

**Comment by cbrnix** [comment] 2019-09-23 06:07
the only option is to make colored icons for small sizes as symbols.  But how this will affect other applications, I do not know

**Comment by germanfr** [comment] 2019-09-23 06:36
Elementary and other themes do that. There will be no problem with making them coloured. And it will look fantastic with the style of this theme, which I like a lot. This theme is very similar to elementary. You can try it to get some inspiration.

**Comment by PJSingh5000** [comment] 2019-09-27 02:59
Icons themselves are not intelligent. They are just files in a folder. The OS will use *all* of the icons in the specified parent folder (under `/usr/share/icons`) for the active icon theme, for *everything*, regardless of the background color of the widget where the icon is rendered.

If the OS theme has mixed light and dark elements, as some modern themes have, the icons look fine in some widgets but not in others. I've seen this issue with Materia, Adapta, and Arc, where they have dark header-bars and UI elements, while other widgets have light backgrounds. Keep in mind, "light" or "normal" icons are actually drawn with dark lines and are suitable for light colored widgets; "dark" icons are actually drawn with light lines and are suitable for light colored widgets. (I'm sure you already know this).

The real solution to this problem is for the UI framework (GTK, QT, etc.) to dynamically determine if a widget has a light or dark background, and then pick icons (from the correct folder under `/usr/share/icons`) that are are suitable for that background. I've been contemplating opening a bug in GTK to request such a feature.

(Of course, this would require icon themes to have a standard way of identifying themselves as light or dark. This isn't an issue, because the current convention seems to be for icon themes to add the "-dark" suffix at the end of the theme's name. Newaita, Papirus, and many others already do this. The UI framework would simply mandate compatible themes to follow this convention, so it can find the correct icon "style").

Thus, the correct fix for this would be in the UI framework, such as GTK, QT, etc. For an icon theme designers, this fix would be transparent, as long as they followed the folder naming convention. Considering how popular "hybrid" dark/light UI themes are, I'm surprised this has not been implemented yet.

**Comment by demoy** [comment] 2019-09-27 03:52
@cbrnix maybe you could incorporate some the suggestion of #112 by making the smaller icon bright color-gradients (I can include screenshot of some icon themes if your not sure what I mean). I would also eliminate the "need" for 2 icon themes. If I understand #114 that should cover it too. 

I do find this to be a humorous solution. I never initially liked the gradient color icon that Calibre took up to avoid black and white theme difference, but after using Calibre so much its pleasant to see know.

**Comment by germanfr** [comment] 2019-09-27 06:12
I wish you could do something like this. Here icons are visible everywhere (in the panel which is dark, and in the folder which is white) and still "readable" even though they are small.

![Screenshot from 2019-09-27 08-07-52](https://user-images.githubusercontent.com/10391266/65746175-61490080-e0fe-11e9-8942-02b344c09908.png)

**Comment by PJSingh5000** [comment] 2019-09-28 00:31
germanfr, demoy,

Try this:

```
sudo mv /usr/share/icons/Newaita-dark/places/16 /usr/share/icons/Newaita-dark/places/16.original
sudo cp -r /usr/share/icons/Newaita/places/16 /usr/share/icons/Newaita-dark/places/

sudo mv /usr/share/icons/Newaita-dark/places/22 /usr/share/icons/Newaita-dark/places/22.original
sudo cp -r /usr/share/icons/Newaita/places/22 /usr/share/icons/Newaita-dark/places/
```

Then chose the Newaita-dark icon theme as your theme.

To revert:

```
sudo rm -rf /usr/share/icons/Newaita-dark/places/16
sudo mv /usr/share/icons/Newaita-dark/places/16.original /usr/share/icons/Newaita-dark/places/16

sudo rm -rf /usr/share/icons/Newaita-dark/places/22
sudo mv /usr/share/icons/Newaita-dark/places/22.original /usr/share/icons/Newaita-dark/places/22
```

If this generally works for you, instead of copying the whole directories for the 16px and 22px icons, you might want to simply pick out the less than dozen icons, that are appear in the filechooser screen shot in https://github.com/cbrnix/Newaita/issues/128#issue-496766362, and copy them from the light theme into your dark theme.

Please, note, I haven't tried this on my current system, since I am not using a "hybrid light/dark" theme like you are, but I hope it will help with your problem. :)

**Comment by demoy** [comment] 2019-09-28 00:49
This is not an issue for me, was trying to come up with a CoLorFul solution.

**Comment by germanfr** [comment] 2019-09-28 05:49
@PJSingh5000 that doesn't solve it. It worsens it. Mixed black and white icons in the same place. 

I think that what @demoy and I have proposed is a very elegant solution.

**Closed** 2020-03-23 11:51 UTC
